%% Setting general paths
addpath(genpath('/home/canal/matlab/'))
%addpath(genpath('/usr/local/mdsplus/matlab'))
%addpath(genpath('/home/zwinglio/MatLab'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/Programas'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/Programas/AC'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/Programas/Analise_Espectral'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/Programas/Burst'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/Programas/PDF'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/Programas/Recurrence'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/Programas/TCABR'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/_Wanderley'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/TCABR/DisparosMat'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/TCABR/RakeMat'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/TCABR/TCABRJE'))
%addpath(genpath('/home/zwinglio/Plasma/Dados/TCABR/tcabrMDSplus'))

%% Setting figure style
set(0,'defaultFigureColor',[1 1 1])
set(0,'defaultaxesfontname','Times')
set(0,'defaultaxesfontsize',16)
set(0,'DefaultAxesFontWeight','bold')
set(0,'DefaultAxesXGrid','on')
set(0,'DefaultAxesYGrid','on')
set(0,'DefaultAxesbox','on')
%set(gca, 'YTickLabel', num2str(get(gca, 'YTick')', '%0.2f'))
%set(gca, 'XTickLabel', num2str(get(gca, 'XTick')', '%0.2f'))